### PR TITLE
Check for existence / modification-status of files before uploading.

### PR DESCRIPTION
**Pull request by cameronyule**
Hi, I've made a small modification to S3Uploader#upload_from_glob which checks if a file exists or has been modified before uploading to S3.

Thanks for the useful project :)

Cheers,
Cameron

### CODE REVIEW

**Comment by cblavier** [comment]
Works fine, I second this pull request :)

**Comment by jacquescrocker** [comment]
cool, pulling now. i'll get a new gem released asap

**Comment by miloops** [comment]
I love the idea, it's pretty unusable to _me_ without it. I've a big app and I can't be uploading everything every time I deploy.

Anyway I did try this patch and it seems to work but rarely... just in a few images, not all of them and it won't work for me on compiled css/js.

**Comment by cameronyule** [comment]
@miloops - That's interesting. I'm using this on a project with hundreds of assets I'm deploying to S3, including Jammit compiled CSS/JS, and haven't experienced that problem.

Are your compiled CSS/JS files definitely changing (e.g. a diff with a previous version detects changes)? The patch hashes entire files so I'm unsure why the hash wouldn't change if the contents of the file had.

**Comment by miloops** [comment]
OMG, tried again and images weren't uploaded ("file has not changed"), don't know what happened before, because i did try it many times. Anyway, it's working now.

Although css/js are being uploaded because they are changing, I think this is jammit's issue, since I didn't modify any css/js and they are being rebuilt.

"For speedy builds, jammit will check the modification times of your packages and source files: only the packages that have changed are rebuilt."

**Comment by cameronyule** [comment]
@miloops Cool, glad it's working :)

**Pull request closed without merging**
